name=input("What's your name, babe?")
food=input("What's your fav food?")
mu=input("What's your go to music?")
loc=input("where do you live?")
print()
print("So you are.." +name)
print("Love to have "+food)
print(mu+" is your jam")
print("And you live in the beautiful "+loc)
print("That sounds amazing!!")
